name: Test

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - ready_for_review
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: bastienb69/formation
      credentials:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: composer install
        run: composer install
      - name: Test
        run: bin/phpunit
